### ISSUE TITLE
Support for tokio-postgres = "0.6"

### ISSUE THREAD

**Issue by shiftrtech** [dac-gmbh/serde_postgres#7]

**Comment by OtterCode** [comment]
Should be fixed by PR #8

**Comment by benjammin12** [comment]
Is anything going on with this?

**Comment by zoombinis** [comment]
what version is supported by `serde_postgres`? I am getting error with the example:

>serde_postgres::from_rows(&rows)?;
^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `tokio_postgres::row::Row`, found struct `tokio_postgres::Row`

I am using:
```toml
tokio-postgres = { version = "0.7.2" }
serde_postgres = "0.2.0"
```
